coe_hw:
  type: "itia/control/FakeHwIfaceNodelet"
  joint_names:
  - linear_motor_cursor_joint

  initial_position: [0.1]

  remap_source_args:
  - "/coe_hw/js_pub/joint_states"
  remap_target_args:
  - "/elmo/joint_states"

  js_pub:
    type: ros/control/JointStatePublisher
    controlled_joint:
    - linear_motor_cursor_joint

  homing_linear_motor_cursor_joint:
    type:        itia/control/HomingController
    joint_name: "linear_motor_cursor_joint"

  open_loop_controller:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/ur5/joint_pos_target"
    controlled_joint: "linear_motor_cursor_joint"

  ctrl0:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "linear_motor_cursor_joint"

  linkpos_to_vel_jnt0:
    type: "itia/control/PositionToVelocityController"

    controlled_joint: "linear_motor_cursor_joint"
    setpoint_topic_name: "/ur5/joint_pos_target"
    use_target_velocity: true
    antiwindup_ratio: 1.0 #antiwindup_ratio = T_t/T_i
    position_maximum_error: 0.05
    position_minimum_error: 0.001
    pos_filter: {type: unity}
    target_pos_filter: {type: unity}
    controller: {type: "proportional", proportional_gain: 2.0}
    integral_controller: {type: "proportional", proportional_gain: 0.0}
    interpolate_setpoint: true
    maximum_interpolation_time: 0.01
    maximum_velociy: 0.75




  joint_teleop:
    type: "itia/control/JointTeleopController"
    message_timeout: 0.100 #time interval where the last message is consired valid, then the speed is set to zero
    controlled_joints:
    - linear_motor_cursor_joint
    maximum_velocity: 0.01

