planner_hw:
  type: "itia/control/TopicHwIfaceNodelet"
  joint_names:
  - linear_motor_cursor_joint
  - ur5_shoulder_pan_joint
  - ur5_shoulder_lift_joint
  - ur5_elbow_joint
  - ur5_wrist_1_joint
  - ur5_wrist_2_joint
  - ur5_wrist_3_joint
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic: "/joint_states"
  command_joint_state_topic:  "/manipulator/joint_target"
  sampling_period: 0.002
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/result"
  - "/planner_hw/thor_prefilter_planner/follow_joint_trajectory/status"
  - "/planner_hw/thor_prefilter_planner/unscaled_joint_target/joint_states"

  remap_target_args:
  - "/ur5/follow_joint_trajectory/cancel"
  - "/ur5/follow_joint_trajectory/feedback"
  - "/ur5/follow_joint_trajectory/goal"
  - "/ur5/follow_joint_trajectory/result"
  - "/ur5/follow_joint_trajectory/status"
  - "/unscaled_joint_target"

  thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    spline_order: 1
    controlled_joint:
    - linear_motor_cursor_joint
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint


  joint_teleop:
    type: "itia/control/JointTeleopController"
    setpoint_topic_name: "/manipulator/target_joint_state"

  cart_teleop:
    type: "itia/control/CartTeleopController"
    setpoint_topic_name: "/manipulator/target_twisted_stamped"
    base_link: "world"
    tool_link: "tool0"
    
