control_configurations:
- name: "watch"
  components:
  - {hardware_interface: "ur5_hw", controller: "js_pub", description: ""}
  - {hardware_interface: "coe_hw", controller: "js_pub", description: ""}
  - {hardware_interface: "planner_hw", controller: "js_pub", description: ""}
- name: "ctrl"
  depends: ["watch"]
  components:
  - {hardware_interface: "ur5_hw", controller: "ctrl1", description: ""}
  - {hardware_interface: "ur5_hw", controller: "ctrl2", description: ""}
  - {hardware_interface: "ur5_hw", controller: "ctrl3", description: ""}
  - {hardware_interface: "ur5_hw", controller: "ctrl4", description: ""}
  - {hardware_interface: "ur5_hw", controller: "ctrl5", description: ""}
  - {hardware_interface: "ur5_hw", controller: "ctrl6", description: ""}
  - {hardware_interface: "coe_hw", controller: "ctrl0", description: ""}
- name: "trajectory_tracking"
  depends: ["ctrl"]
  components:
  - {hardware_interface: "planner_hw", controller: "microinterpolator", description: ""}

