coe_hw:
  type: cnr/control/FakeRobotHW
  appenders: [file, screen]
  levels: [trace, info]
  pattern_layout: "[%5p][%d{HH:mm:ss,SSS}][%50M:%04L][%24c] %m%n"
  file_name: "coe_hw"
  sampling_period: 0.001
  diagnostic_period: 0.1
  maximum_missing_cycles: 20
  feedback_joint_state_timeout: 10
  joint_names:
  - linear_motor_cursor_joint


  initial_position: [0.1]

  remap_source_args:
  - "/coe_hw/js_pub/joint_states"
  remap_target_args:
  - "/elmo/joint_states"
