ur5_hw:
  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: world
    tool_link: ur5_tool0
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning


  force_torque_sensor_controller:
     type:         force_torque_sensor_controller/ForceTorqueSensorController
     publish_rate: 125

  ctrl1:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_shoulder_pan_joint"

  ctrl2:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_shoulder_lift_joint"

  ctrl3:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_elbow_joint"

  ctrl4:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_wrist_1_joint"

  ctrl5:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_wrist_2_joint"

  ctrl6:
    type:        itia/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_wrist_3_joint"




  thor_prefilter_planner:
    type: "thor/PrefilterPosVelEffController"
    controlled_joint:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
    spline_order: 1
