ur5_hw:
  remap_source_args:
  - "/ur5_hw/js_pub/joint_states"
  remap_target_args:
  - "/ur5/joint_states"

  js_pub:
    type: cnr/control/JointStatePublisher
    controlled_joint: all
    base_link: ur5_base_link
    tool_link: ur5_tool0
    robot_description_param: /robot_description
    robot_description_planning_param: /robot_description_planning


  force_torque_sensor_controller:
     type:         force_torque_sensor_controller/ForceTorqueSensorController
     publish_rate: 125

  ctrl1:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_shoulder_pan_joint"
    enable_setpoint_watchdog: false

  ctrl2:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_shoulder_lift_joint"
    enable_setpoint_watchdog: false

  ctrl3:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_elbow_joint"
    enable_setpoint_watchdog: false

  ctrl4:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_wrist_1_joint"
    enable_setpoint_watchdog: false

  ctrl5:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_wrist_2_joint"
    enable_setpoint_watchdog: false

  ctrl6:
    type:        cnr/control/OpenLoopPositionController
    setpoint_topic_name: "/manipulator/joint_target"
    controlled_joint: "ur5_wrist_3_joint"
    enable_setpoint_watchdog: false
